<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.qpzm7903</groupId>
    <artifactId>javademo</artifactId>
    <version>1</version>
    <packaging>pom</packaging>
    <properties>
        <java.version>17</java.version>
    </properties>
    <modules>
        <module>3rdDependencies</module>
        <module>annotation</module>
        <module>classLoaderDemo</module>
        <module>designPattern</module>
        <module>druid-demo</module>
        <module>flyway-h2-demo</module>
        <module>h2demo</module>
        <module>iocdemo</module>
        <module>javabasicdemo</module>
        <module>junit5demo</module>
        <module>log4jdemo</module>
        <module>mockitodemo</module>
        <module>mybatis-h2-demo</module>
        <module>ognl_demo</module>
        <module>slf4j-demo/slf4jdemo</module>
        <module>spring-mybatis-demo</module>
        <module>spring-reactive-demo</module>
        <module>spring_test_demo</module>
        <module>spring_ut_test</module>
        <module>spring_security_user_jdbc</module>
        <module>transaction-demo</module>
        <module>mockito_demo</module>
        <module>maven-plugin-demo</module>
        <module>slf4j-demo</module>
        <module>resilience4j-demo/my-http-client</module>

    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.qpzm7903</groupId>
                <artifactId>3rdDependencies</artifactId>
                <version>1.0-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

<!--    TODO 插件似乎只能在父pom里指定-->
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M7</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>