spring.application.name=transaction-demo
# spring.datasource.druid.url=jdbc:mysql://192.168.100.1:3306/transaction
spring.datasource.druid.url=jdbc:mariadb://192.168.100.1:3306/transaction
spring.datasource.druid.password=mysql_F5zJYw
spring.datasource.druid.username=root
spring.datasource.druid.validation-query=select 1
#spring.datasource.druid.connect-timeout=0
#spring.datasource.druid.socket-timeout=0
#spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.druid.driver-class-name=org.mariadb.jdbc.Driver
mybatis.mapper-locations=classpath:mapper/*
spring.main.allow-bean-definition-overriding=true
spring.flyway.enabled=false